CREATE USER "andrei" WITH ENCRYPTED PASSWORD 'andrion1234';
GRANT ALL PRIVILEGES ON DATABASE andrion TO "andrei";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "andrei";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "andrei";